/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.lpoo.view;

import br.edu.ifsul.lpoo.control.PersistenciaJPA;
import br.edu.ifsul.lpoo.model.Funcionarios;
import br.edu.ifsul.lpoo.model.Tipo_Funcionarios;
import javax.swing.JOptionPane;
/**
 *
 * @author Jennifer Ebertz
 */
public class TelaFuncionariosJF extends javax.swing.JFrame {

    PersistenciaJPA jpa;
    Funcionarios funcionario = new Funcionarios();
    
    public void setFuncionario(Funcionarios f){
    funcionario = f;
    lblNomeFuncionario.setText(funcionario.getNome());
    }
    
    /**
     * Creates new form TelaFuncionariosJF
     */
    public TelaFuncionariosJF() {
        jpa = new PersistenciaJPA();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        lblBemVindo = new javax.swing.JLabel();
        lblNomeFuncionario = new javax.swing.JLabel();
        btnCaixaEletronico = new javax.swing.JButton();
        BtnNovoFunc = new javax.swing.JButton();
        btnNovoCliente = new javax.swing.JButton();
        btnAgencia = new javax.swing.JButton();
        btnContas = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBemVindo.setText("Bem Vindo!!");

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCaixaEletronico.setText("Abrir Caixa Eletronico");
        btnCaixaEletronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaEletronicoActionPerformed(evt);
            }
        });

        BtnNovoFunc.setText("Cadastrar Novo Funcionário");
        BtnNovoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoFuncActionPerformed(evt);
            }
        });

        btnNovoCliente.setText("Cadastrar Novo Cliente");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnAgencia.setText("Ver Agencias");
        btnAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenciaActionPerformed(evt);
            }
        });

        btnContas.setText("Ver Contas");
        btnContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContasActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblBemVindo)
                            .addGap(18, 18, 18)
                            .addComponent(lblNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnContas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNovoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCaixaEletronico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnNovoFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnCaixaEletronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnNovoFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaixaEletronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaEletronicoActionPerformed
     TelaLoginCliente logincliente = new TelaLoginCliente();
     logincliente.setVisible(true); 
    }//GEN-LAST:event_btnCaixaEletronicoActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
     if (!(funcionario.getTipoFuncionario().equals(Tipo_Funcionarios.Atendente))) {
     VerClientesJF telacliente = new VerClientesJF();
     telacliente.setVisible(true);
     }else{
         JOptionPane.showMessageDialog(this, "Você não tem permissão para acessar esta funcionalidade.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void BtnNovoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoFuncActionPerformed
        // TODO add your handling code here:
     if (funcionario.getTipoFuncionario().equals(Tipo_Funcionarios.Gerente) ||
    funcionario.getTipoFuncionario().equals(Tipo_Funcionarios.Supervisor)) {
     VerFuncionariosJF telafunc = new VerFuncionariosJF();
     telafunc.setVisible(true);
     }else{
         JOptionPane.showMessageDialog(this, "Você não tem permissão para acessar esta funcionalidade.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
     }
        
    }//GEN-LAST:event_BtnNovoFuncActionPerformed

    private void btnAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenciaActionPerformed
       if (funcionario.getTipoFuncionario().equals(Tipo_Funcionarios.Supervisor)) {
     VerAgencias telaAgencia = new VerAgencias();
     telaAgencia.setVisible(true);
     }else{
         JOptionPane.showMessageDialog(this, "Você não tem permissão para acessar esta funcionalidade.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_btnAgenciaActionPerformed

    private void btnContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContasActionPerformed
        if (funcionario.getTipoFuncionario().equals(Tipo_Funcionarios.Gerente) ||
    funcionario.getTipoFuncionario().equals(Tipo_Funcionarios.Supervisor)) {
     VerContas telaContas = new VerContas();
     telaContas.setVisible(true);
     }else{
         JOptionPane.showMessageDialog(this, "Você não tem permissão para acessar esta funcionalidade.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_btnContasActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaInicialJF inicio = new TelaInicialJF();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionariosJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionariosJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNovoFunc;
    private javax.swing.JButton btnAgencia;
    private javax.swing.JButton btnCaixaEletronico;
    private javax.swing.JButton btnContas;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblNomeFuncionario;
    // End of variables declaration//GEN-END:variables


}
